### ISSUE TITLE
The applications didn't have forgot-password.html page which is referred in signin pages

### ISSUE THREAD

**Issue by vakasapu** [creativetimofficial/ct-impact-design-system-pro#3]
<div><a href="./forgot-password.html" class="small text-right">Lost password?</a></div>

When we click on Lost Password there is no forgot password page to redirect it

**Comment by zoltanszogyenyi** [comment]
@vakasapu We'll create a page for this and it will be released tomorrow for v1.1.

**Comment by zoltanszogyenyi** [comment]
@vakasapu  Until we roll out the v1.1 update, please use the following code to create the password reset pages:

password-reset-email.html -> https://pastebin.com/5AP8amvC
password-reset.html -> https://pastebin.com/8tKsHk7j

There are two pages because with the first one you need to send an email to the user and the second page is used when the email has been sent to the user.

Thanks!

**Comment by zoltanszogyenyi** [comment]
This has been added in version 1.1.
